name: release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.4
      - name: Download Go modules
        run: go mod download
      - name: Build binaries
        run: make build
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          path: bin/*

  release:
    name: Run release-please
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
      - name: Show release info
        run: |
          echo "Release created?  ${{ steps.release.outputs.release_created }}"
          echo "Tag name:  ${{ steps.release.outputs.tag_name }}"
          echo "Release notes body:  ${{ steps.release.outputs.body }}"
      - name: Upload dingopie.exe to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/dingopie.exe
          asset_name: dingopie.exe
          asset_content_type: application/octet-stream
      - name: Upload dingopie.bin to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/dingopie.bin
          asset_name: dingopie.bin
          asset_content_type: application/octet-stream